server:
  port: 9000

hostname: localhost:${server.port}

spring:
  datasource:
    url: jdbc:postgresql://localhost/pechkin
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout:
      seconds: 900

security:
  jwt:
    secret: "pochtalion"
    expired: "1800000"