server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pechkin
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always


security:
  jwt:
    secret: "pochtalion"
    expired: "1800000"
